# Generated by Django 4.2.7 on 2024-04-30 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Summary1', models.CharField(max_length=1000)),
                ('Summary2', models.CharField(max_length=800)),
            ],
        ),
    ]
