# Generated by Django 4.2.7 on 2024-04-30 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Summary1',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='job',
            name='Summary2',
            field=models.CharField(max_length=2000),
        ),
    ]
